apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: expense
  labels:
    app: nginx
    tier: web
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.imageVersion}}
        ports:
        - containerPort: 80




